"""Add role column to users

Revision ID: a2df5426c5b4
Revises: 7cf8caee002a
Create Date: 2024-12-27 17:30:34.583519

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2df5426c5b4"
down_revision: Union[str, None] = "7cf8caee002a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", sa.String(), nullable=True))
    op.drop_constraint("users_group_id_fkey", "users", type_="foreignkey")
    op.drop_column("users", "group_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "users_group_id_fkey", "users", "groups", ["group_id"], ["id"]
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###
